input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}


filter {
  if "sudo" in [message] {
    grok {
      match => {
	"message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:hostname} %{WORD:user} sudo: pam_unix\(%{DATA:pam_service}\): %{GREEDYDATA:sudo_message}"
      }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  } else if "pam_unix" in [message] {
    grok {
      match => {
        "message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:hostname} %{DATA:service}]: pam_unix\(%{DATA:pam_service}:auth\): %{GREEDYDATA:auth_message}"
      }
    }
    kv {
      source => "auth_message"
      field_split => " "
      value_split => "="
      trim_key => " "
      trim_value => " "
    }
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }

    grok {
      match => {
        "auth_message" => [
          "Accepted password for %{DATA:logname} from %{IP:src_ip} port %{NUMBER:port} %{GREEDYDATA}",
          "Failed password for %{DATA:logname} from %{IP:src_ip} port %{NUMBER:port} %{GREEDYDATA}"
        ]
      }
      overwrite => ["logname", "src_ip", "port"]
    }

#    geoip {
#      source => "src_ip"
#      target => "geoip"
#      database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
#    }
  }
}	
output {
  if "Failed password" in [message] {
    email {
      to => "heaheagirl@naver.com"
      from => "heaheagirl@naver.com"
      subject => "Login Failure Alert on %{host}"
      body => "A failed login attempt detected.\nHost: %{hostname}\nMessage: %{auth_message}"
      address => "smtp.naver.com"
      port => 587
      username => "heaheagirl@naver.com"
      password => "PB811E31JUCJ"
      authentication => "login"
      use_tls => true
      debug => true
    }
  }
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "utm-logs-test"
  }
}

